### PR TITLE
Setup GitHub Actions

### PR DESCRIPTION
**Pull request by LukePrior**
I have configured GitHub Actions to check that frontend code will compile with TSC and that it passes ESLint Standard style.

### CODE REVIEW

**Comment by LukePrior** [comment]
@omeh-a Do you have a clue how I get rid of all the commits I did a squash but the old ones remain

**Comment by omeh-a** [comment]
> @omeh-a Do you have a clue how I get rid of all the commits I did a squash but the old ones remain?

Just squash as you merge - doing the squash step ahead of time weirds out often

**Comment by LukePrior** [comment]
Well it's ready to go so if you could do that it would be great!

**Comment by LukePrior** [comment]
Cheers

**Pull request merged**
